# Automotive LLM System Configuration

# Audio processing settings
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  input_device_index: null  # Auto-detect
  wake_word_sensitivity: 0.7
  noise_reduction: true

# Vehicle interface settings
vehicle:
  obd_port: "/dev/ttyUSB0"
  obd_baudrate: 38400
  can_channel: "can0"
  can_bitrate: 500000
  enable_obd: true
  enable_can: true
  vehicle_make: "generic"
  vehicle_model: "classic"
  vehicle_year: 1970

# Large Language Model settings
llm:
  model_name: "llama3.1:8b-instruct-q4_K_M"
  ollama_host: "http://localhost:11434"
  max_tokens: 512
  temperature: 0.7
  context_window: 4096
  enable_hailo: true

# Safety monitoring settings
safety:
  enable_monitoring: true
  monitoring_interval: 1.0
  engine_temp_warning: 105.0    # 째C
  engine_temp_critical: 110.0   # 째C
  max_boost_pressure: 20.0      # PSI
  max_rpm: 7000.0              # RPM
  emergency_mode_enabled: true

# HVAC system settings
hvac:
  min_temperature: 16.0  # 째C
  max_temperature: 32.0  # 째C
  max_fan_speed: 8
  auto_mode_enabled: true
  dual_zone: false

# Logging configuration
logging:
  level: "INFO"
  file_path: "/var/log/automotive-llm/system.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  enable_console: true
  enable_file: true

# System settings
system:
  device_name: "automotive-llm"
  enable_api: false
  api_port: 8000
  data_directory: "/var/lib/automotive-llm"
  config_directory: "/etc/automotive-llm"
  enable_systemd: true